// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDygv2OaaMEtf74hoD6cgPnlSlKeMQlo_s',
    appId: '1:902830448640:web:a9b3992fb9587801be78e5',
    messagingSenderId: '902830448640',
    projectId: 'xyz01-5be67',
    authDomain: 'xyz01-5be67.firebaseapp.com',
    storageBucket: 'xyz01-5be67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHDV6ljuQOO6RQ80To12-WKPgVFZHCsqM',
    appId: '1:902830448640:android:6cd00a92138de1e7be78e5',
    messagingSenderId: '902830448640',
    projectId: 'xyz01-5be67',
    storageBucket: 'xyz01-5be67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcowIzckMB4AmWTSe6NaGKlbhQx92b7iA',
    appId: '1:902830448640:ios:76195ee4ca2a45d7be78e5',
    messagingSenderId: '902830448640',
    projectId: 'xyz01-5be67',
    storageBucket: 'xyz01-5be67.appspot.com',
    iosClientId: '902830448640-20ug3pl1o3fqbdcp8ilfaskkggeuc2mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.sarbu',
  );
}
